apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.2/manifests/install.yaml

namespace: argocd

# patches:
# - target:
#   path: patches/node-selectors.yaml