---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivial-nginx-app
  template:
    metadata:
      labels:
        app: trivial-nginx-app
    spec:
      containers:
      - name: webserver-simple
        image: nginx:1.26.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
