apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: tenant-b-gitops-docker
  labels:
    app: hello-microservice
    tenant: tenant-b
    version: v1
  name: sa-nginx
---
apiVersion: v1
kind: Service
metadata:
  namespace: tenant-b-gitops-docker
  name: svc-nginx-service
spec:
  type: ClusterIP
  selector:
    app: nginx
    tenant: tenant-b
    version: v1
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tenant-b-gitops-docker
  labels:
    app: nginx
    tenant: tenant-b
    version: v1
  name: deploy-nginx
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
      tenant: tenant-b
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      namespace: tenant-b-gitops-docker
      labels:
        app: nginx
        tenant: tenant-b
        version: v1
    spec:
      containers:
      - name: nginx
        image: nginx:1.24.0 
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "0.2"
            memory: "128Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"  
      serviceAccountName: sa-nginx
